# These are supported funding model platforms

github: [user1, user2]
patreon: user1
open_collective: Mr-Cai
ko_fi: Ko-fi
tidelift: git/fun_refresh
community_bridge: fun_refresh
custom: https://raw.githubusercontent.com/Mr-Cai/Util-Res/master/pic/%E8%B5%9E%E8%B5%8F.png
